### ISSUE TITLE
Add ipv6 support

### ISSUE THREAD

**Issue by Bull3time** [tmobile/stf_ios_support#10]
Mirror feed does not support binding to interfaces that create ipv6 addresses, for example en0 on a mac.  

```
Listening on fd7b:8e4a:f5b3:0:8c23:78e6:c0a6:8803:8000
Opening incoming video: video_pipes/pipe_8000
Receiving incoming video
2020/01/03 22:15:57 listen tcp: address fd7b:8e4a:f5b3:0:8c23:78e6:c0a6:8803:8000: too many colons in address
```

**Comment by nanoscopic** [comment]
The latest updates to mirrorfeed use the same code to do interface/name to IP address that is used in the main project. That should prevent it from trying to listen on IPv6 address.

Many/most IPv6 network interfaces also listen on IPv4. That is almost always the case for localhost / en0. As a result, this change should work for the example given.

I'm not sure that all the components used by stf_ios_support ( such as WDA ) supporting running in only IPv6 mode, so it is unlikely that serious effort will be given to running in a pure IPv6 fashion anytime soon. I will continue to leave this ticket open though, since it could foreseeably happen in the future.

For now the focus will be on making everything work with interfaces that have dual IPv4 / IPv6 addresses; and using the IPv4 side.

**Comment by nanoscopic** [comment]
Have fully tested out running everything on a single machine. It works using non-localhost interfaces currently.

Using localhost/en0 will not be supported and is an issue for other reasons.
