### ISSUE TITLE
"parse error: Invalid numeric literal at line 1, column 3" while execute make dist

### ISSUE THREAD

**Issue by renatodefarias** [tmobile/stf_ios_support#17]
Hello,

Im trying to execute make dist command, but i got that error in my terminal:

> parse error: Invalid numeric literal at line 1, column 3
> parse error: Invalid numeric literal at line 1, column 3
> git clone  repos/WebDriverAgent --branch
> error: option `branch' requires a value
> make: *** [repos/WebDriverAgent] Error 129

Any idea for this error?

Thanks!

**Comment by renatodefarias** [comment]
config.json:

`// Minimal Example
{
  "xcode_dev_team_id": "my_code_dev_team_id",
  "stf": {
    "ip": "my_id",
    "hostname": "my_hostname"
  },
  "video": {
    "enabled": true,
    "use_vnc": true,
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 10
  },
  "install": {
    "root_path": "/Users/digitaltest/Documents/openstf-ios",
    "config_path": "config.json",
  },
  "vpn": {
    "type": "none",
    "ovpn_config": "[path to your openvpn config file]"
  }
}

// Defaults
{
  "wda_folder": "./bin/wda",
  "xcode_dev_team_id": "",
  "network": {
    "coordinator_port": 8027,
    "video": "8000-8005",
    "dev_ios": "9240-9250",
    "vnc": "5901-5911",
    "wda": "8100-8105",
    "interface": "en0"
  },
  "stf": {
    "ip": "",
    "hostname": ""
  },
  "video": {
    "enabled": true,
    "use_vnc": false,
    "vnc_scale": 2,
    "vnc_password": "",
    "frame_rate": 5
  },
  "install": {
    "root_path": "",
    "config_path": "",
  },
  "log": {
    "main": "logs/coordinator",
    "proc_lines": "logs/procs",
    "wda_wrapper_stdout": "./logs/wda_wrapper_stdout",
    "wda_wrapper_stderr": "./logs/wda_wrapper_stderr"
  },
  "vpn": {
    "type": "openvpn",
    "ovpn_working_dir": "/usr/local/etc/openvpn",
    "tblick_name": ""
  },
  "bin_paths": {
    "wdaproxy": "bin/wdaproxy",
    "device_trigger": "bin/osx_ios_device_trigger",
    "video_enabler": "bin/osx_ios_video_enabler",
    "mirrorfeed": "bin/mirrorfeed",
    "openvpn": "/usr/local/opt/openvpn/sbin/openvpn",
    "iproxy": "/usr/local/bin/iproxy",
    "wdawrapper": "bin/wda_wrapper",
    "ffmpeg": "bin/ffmpeg"
  },
  "repos": {
    "stf": "https://github.com/nanoscopic/stf-ios-provider.git",
    "wda": "https://github.com/appium/WebDriverAgent.git"
  }
}`

**Comment by nanoscopic** [comment]
The two sections in the example file are two different examples. The "minimal example" can be copied to config.json to have a basic a setup, changing it as needed.

The "defaults" example is shown in order to demonstrate all the possible options that can be set, and what the default values will be if you don't specify a certain field.

JSON configuration files must start with a single brace `{` and end with a brace `}`; a single JSON file cannot contain two different such sections.

The "minimal example" should perhaps be improved some also to make it easier to get started. The example has `use_vnc` set to true. That will only work if your IOS device is jailbroken and has Veency installed on it. If you have not done that, you should have `use_vnc` set to false.

Also, in the example anything that is shown as "[some description]" needs to be filled out. Your config.json file doesn't have `root_path` or `config_path` set.

Finally, it is very likely that `vpn.type` should be set to `none`.

I will update the basic example to be more suitable.

**Comment by renatodefarias** [comment]
Dear @nanoscopic ,

Thanks for reply, i'll update my json with this infos and try again.

Thank you a lot!

**Comment by renatodefarias** [comment]
Closing this issue, fixed adjusting the json file using minimal example.

thanks!!
