### ISSUE TITLE
Open VPN is not Running

### ISSUE THREAD

**Issue by bikee1235** [tmobile/stf_ios_support#19]
Hi 

after running 

./run commnad 

in the log, I am getting this error "OpenVPN is not running "

FATA[0000] OpenVPN is not running                        type=openvpn_not_loaded

is it mandatory to configure openvpn?

**Comment by nanoscopic** [comment]
You will need to set "vpn.type" to be "none" in `config.json` in order to run everything without using VPN. I have pushed an update to stf_ios_support as well now that default VPN to being 'none' so you can simply leave out the 'vpn' section of config.json entirely. That should make it easier and prevent others from being stuck on this same issue.
