### ISSUE TITLE
Feature Request - Enable port 8000 video debug interface

### ISSUE THREAD

**Issue by bikeebh** [tmobile/stf_ios_support#27]
Hi 
When I connect the device from a UI device screen is not showing
And When I open this "http://172.16.50.111:8000/"  URL
video is  showing  interaction is not there

wda and other process are running for that device

what could be the reason?

Thanks

**Comment by nanoscopic** [comment]
The port 8000 "interface" was never fleshed out completely to work / show anything. As such it is expected currently that is does nothing right now. It has been left in because it is a feature that will at some point be completed.

The only way to see video currently is to use STF interface to do so.

WDA doesn't serve video and is somewhat unrelated. Video can function and stream properly even if WDA doesn't work.

The following lines should be output from coordinator ( ./run ) when video is "working":
```
INFO[0002] Video - interface available                   dev_name=Iphone6475 dev_uuid=x type=vid_interface
INFO[0002] Process start - mirrorfeed                    mirrorfeed_bin=bin/mirrorfeed pipe=video_pipes/pipe_8000 port=8000 proc=mirrorfeed tunName=en0 type=proc_start uuid=x
INFO[0002] Process start - ffmpeg                        ops="[-f avfoundation -i Iphone6475 -pixel_format bgr0 -f mjpeg -bsf:v mjpegadump -bsf:v mjpeg2jpeg -r 10 -vsync 2 -nostats pipe:1]" proc=ffmpeg type=proc_start uuid=x
INFO[0002] Video - first frame                           height=1334 proc=mirrorfeed type=first_frame uuid=x width=750
```

The most important log message here is "Video - first frame". If you see that, it means that the mirrorfeed program has successfully captured an image via ffmpeg from your IOS device. If you don't see that message; it won't work.

To see why, use `./view_log -proc ffmpeg` and `./view_log -proc mirrorfeed`. There are further diagnostic steps but that is a good start.

**Comment by nanoscopic** [comment]
This is a feature request as the port 8000 interface isn't intended to work currently.

**Comment by nanoscopic** [comment]
Correction; the port 8000 interface does actually work; you just have to click the "Open" button to the right to start the video streaming and showing in the browser. It is still quite hacky but it should function.

I used it during testing of the latest update to video stream that has just been pushed. Please try out the latest version and let me know if you encounter the same issues as before.

**Comment by nanoscopic** [comment]
It works. 🤷
