### ISSUE TITLE
Displaying Incorrect Time, Network  Info 

### ISSUE THREAD

**Issue by bikeebh** [tmobile/stf_ios_support#29]
Hi,

When I am connecting the device 

Time of Device got changed to 9:41 AM

![Screen Shot 2020-03-02 at 19 37 33](https://user-images.githubusercontent.com/49250627/75745304-efc04e80-5d3c-11ea-80c8-504bd4c7a560.png)

Why time and Network Info got changed?

Thanks

**Comment by nanoscopic** [comment]
No idea. Nothing that I am aware of would cause the time to change when the device is connected to STF via WDA.

stf_ios_support only connects to the device in two ways: 1. Through WDA 2. By streaming video

Streaming video certainly wouldn't change the time, so that leaves WDA as a possible cause. All WDA "essentially" does is run some XCUItests against the phone using XCode.

The only thing I can imagine that would cause the time to change is if the phone is connecting to the network your Mac machine is on, and picking up Network time from there. My recommendation to avoid that is to go to the Date & Time settings on your IOS device, and uncheck "Set Autuomatically". That will likely resolve your issue.

**Comment by nanoscopic** [comment]
No response for one month. I don't believe there is an issue with stf_ios_support here as explained. Closing.

**Comment by nanoscopic** [comment]
I found the answer to this bug. It is actually a feature. See https://github.com/danielpaulus/quicktime_video_hack/issues/48#issuecomment-620032464

The battery display will also be shown incorrectly.
