### ISSUE TITLE
storage-temp Cannot create container for service storage-temp: invalid volume specification

### ISSUE THREAD

**Issue by zarashima** [tmobile/stf_ios_support#30]
Hi,

I got the same issue from here: https://github.com/tmobile/stf_ios_support/issues/18. Don't know how to fix it yet :(

I didn't make any changes to docker-compose file and still use the default values

Regards

**Comment by nanoscopic** [comment]
Unfortunately the previous user did not report what he did to "fix" the issue, so I don't know what was done wrong to begin with.

Do you get this portion of the error:
```
invalid mount config for type "volume": invalid mount path: 'data' mount path must be absolute
```

This line of the docker-compose.yml would be the cause:
https://github.com/tmobile/stf_ios_support/blob/master/server/docker-compose.yml#L139

The /app/data within the container should be built automatically by the command specified on the next line: `stf storage-temp --port 3000 --save-dir /app/data`

That folder should be mounted through into the container. The named volume that should be made automatically by docker-compose is at the top: `storage-temp`.

You can create the named volume yourself perhaps in docker first and that may fix your issue. You should read about docker volumes. My guess is that docker failed to create the volume due to some permission issue.

On my machine, after having started up the docker-compose, I see the following output from `docker volume ls`:
```
local     server_storage-temp
```

What do you see when you run `docker volume ls` ?

You can use `docker volume create server_storage-temp` to create the volume manually if it isn't there. If that fails running the command manually should give you an error indicating why it failed.

**Comment by nanoscopic** [comment]
Have not seen any response on fixing this by creating the volume. I am going to assume it is solved unless more information is provided. Feel free to reopen should the direction above not work.

**Comment by devlucy** [comment]
Hi,
`docker volume create server_storage-temp` is not fixing above issue

**Comment by nanoscopic** [comment]
Based on provided information I have no way to fix the problem being encountered. It works on every system I've done it on. This is outside the scope of support of stf_ios_support.

I'd suggest you seek help in a docker forum of some sort. This is likely to be some sort of issue with your specific version of docker and/or the way docker is setup on your machine.

You'll need to provide what OS you are attempting to run this on, the version of docker and it's components etc to anyone attempting to solve this.

**Comment by devlucy** [comment]
Starting setup on new clone worked for me but I followed the same steps. I am attempting it on macOS Catlina with docker v19.03.8. and `docker volume ls `outputs:
```
local               83059f8cedd634f2033c247714aa61dd103d700b2387f159b4de5f7e5f01d788
local               server_rethinkdb
local               server_storage-temp
```
thank you for the support.
