### ISSUE TITLE
docker-compose; rethinkdb not functioning

### ISSUE THREAD

**Issue by haozhexu** [tmobile/stf_ios_support#32]
I'm building iOS device farm using `stf_ios_support`, but I encountered two issues.

When I run `make dist` as the README said, I got:

> git clone  repos/WebDriverAgent --branch 
> error: option `branch' requires a value

Not sure what branch I was supposed to provide?

Also when I run `docker-compose up`, it's mostly fine except:

> 2020-04-03T02:10:23.284Z FTL/reaper 1 [dev] Unable to load initial state { ReqlOpFailedError: Cannot perform read: primary replica for shard ["", +inf) not available in:
> reaper_1                | r.table("devices").getAll(true, {"index": "present"})

Looks like it's looking for a table of devices? Is there something additional I need to provide?

Thanks!

**Comment by nanoscopic** [comment]
The error about missing branch is due to your `config.json` file being invalid JSON; likely because it still contains the "//" comment lines I put in it, which aren't valid JSON according to the Golang JSON parser currently being used. In the near future this will be replaced with a different, more lax parser, to avoid this recurring issue. I am intending to replace the JSON parser with ujsonin ( https://github.com/nanoscopic/ujsonin )

The branch is meant to default to the correct value automatically. You shouldn't have to think about it. It is, by the way, just the master branch that is needed.

I have seen a few people mention encountering issues with rethinkdb when attempting to docker-compose up so far. It has something to do with their setup of docker not properly creating the volume for rethinkdb on intial startup. To fix this I would recommend creating the proper named volume yourself before doing `docker-compse up`.

**Comment by nanoscopic** [comment]
Closing due to lack of response. Reopen if you can show a way to replicate the issue.
