### ISSUE TITLE
Invalid character error when executing the run script

### ISSUE THREAD

**Issue by pespinel** [tmobile/stf_ios_support#38]
After generating a dist with `make dist` and unpacking it inside the offline folder, i execute the run script (Which calls the coordinator binary) and i'm getting the following error:

`FATA[0000] 2 invalid character '}' looking for beginning of object key string`

Commit: 8ce7fe63237909c2271a04e7a016182937d95c42
Branch: origin/master, origin/HEAD

**Comment by pespinel** [comment]
I had badly formatted the config.json, my bad!

**Comment by nanoscopic** [comment]
This is a recurring issue. The JSON parser in Golang not very forgiving, and outputs vague error messages that aren't of much help determining where the issue is in your JSON file. Am going to replace the parser with a different one soon to provide better error output and accept looser json format. ( importantly to allow comments in the JSON )
