### ISSUE TITLE
Add configurable websockets connection type

### ISSUE THREAD

**Issue by Bull3time** [tmobile/stf_ios_support#9]
Currently websockets are hardcoded to be secure (wss) but running stf on a single machine may benefit from being insecure (ws). 

I think this will also allow regular openstf `stf local` to run?

**Comment by nanoscopic** [comment]
I don't think there is any real value in making the setup work without https. It would just add more complexity because it would require an alternate set of configuration files.

I have though added a script for generating a self signed cert to make testing a basic setup easier, and have committed a self signed cert already configured in nginx conf to prevent the need to have to change the config to have a basic setup on a single machine working.

**Comment by nanoscopic** [comment]
Have already changed the provider to support self signed cert for capturing screenshots currently. Also, the server directory includes a pre-created cert for testing using https. Am not going to add unsecured access; there is no need.

If someone else wants to do the work to support it I'd welcome a PR; simply won't be spending the effort to do it myself.
